---
title: "CodeBook"
author: "Ben"
date: "Tuesday, October 21, 2014"
output: html_document
---
Details on the features:
=========================================
The features selected for this database come from the accelerometer and gyroscope 3-axial raw signals timeAcceleration-XYZ and TimeGyro-XYZ. These time domain signals were captured at a constant rate of 50 Hz. Then they were filtered using a median filter and a 3rd order low pass Butterworth filter with a corner frequency of 20 Hz to remove noise. Similarly, the acceleration signal was then separated into body and gravity acceleration signals (TimeBodyAcceleration-XYZ and TimeGravityAcceleration-XYZ) using another low pass Butterworth filter with a corner frequency of 0.3 Hz. 

Subsequently, the body linear acceleration and angular velocity were derived in time to obtain Jerk signals (TimeBodyAccelerationJerk-XYZ and TimeBodyGyroJerk-XYZ). Also the magnitude of these three-dimensional signals were calculated using the Euclidean norm (TimeBodyAccelerationMag, TimeGravityAccelerationMag, TimeBodyAccelerationJerkMag, TimeBodyGyroMag, TimeBodyGyroJerkMag). 

Finally a Fast Fourier Transform (FFT) was applied to some of these signals producing FrequencyBodyAcceleration-XYZ, FrequencyBodyAccelerationJerk-XYZ, FrequencyBodyGyro-XYZ, FrequencyBodyAccelerationJerkMag, FrequencyBodyGyroMag, FrequencyBodyGyroJerkMag.

Details on the original signals:
=========================================
These signals were used to estimate variables of the feature vector for each pattern:  
'-XYZ' is used to denote 3-axial signals in the X, Y and Z directions.

- TimeBodyAcceleration-XYZ
- TimeGravityAcceleration-XYZ
- TimeBodyAccelerationJerk-XYZ
- TimeBodyGyro-XYZ
- TimeBodyGyroJerk-XYZ
- TimeBodyAccelerationMag
- TimeGravityAccelerationMag
- TimeBodyAccelerationJerkMag
- TimeBodyGyroMag
- TimeBodyGyroJerkMag
- FrequencyBodyAcceleration-XYZ
- FrequencyBodyAccelerationJerk-XYZ
- FrequencyBodyGyro-XYZ
- FrequencyBodyAccelerationMag
- FrequencyBodyAccelerationJerkMag
- FrequencyBodyGyroMag
- FrequencyBodyGyroJerkMag

Derived features - mean and standard deviation measurements:
=========================================
The mean and standard deviation of the features generated from the above original signals are denoted as:

- TimeBodyAccelerationMean-XYZ
-	TimeBodyAccelerationStd-XYZ
-	TimeGravityAccelerationMean-XYZ
-	TimeGravityAccelerationStd-XYZ
-	TimeBodyAccelerationJerkMean-XYZ
-	TimeBodyAccelerationJerkStd-XYZ
-	TimeBodyGyroMean-XYZ
-	TimeBodyGyroStd-XYZ
-	TimeBodyGyroJerkMean-XYZ
-	TimeBodyGyroJerkStd-XYZ
-	TimeBodyAccelerationMagMean
-	TimeBodyAccelerationMagStd
-	TimeGravityAccelerationMagMean
-	TimeGravityAccelerationMagStd
-	TimeBodyAccelerationJerkMagMean
-	TimeBodyAccelerationJerkMagStd
-	TimeBodyGyroMagMean
-	TimeBodyGyroMagStd
-	TimeBodyGyroJerkMagMean
-	TimeBodyGyroJerkMagStd
-	FrequencyBodyAccelerationMean-XYZ
-	FrequencyBodyAccelerationStd-XYZ
-	FrequencyBodyAccelerationMeanFreq-XYZ
-	FrequencyBodyAccelerationJerkMean-XYZ
-	FrequencyBodyAccelerationJerkStd-XYZ
-	FrequencyBodyAccelerationJerkMeanFreq-XYZ
-	FrequencyBodyGyroMean-XYZ
-	FrequencyBodyGyroStd-XYZ
-	FrequencyBodyGyroMeanFreq-XYZ
-	FrequencyBodyAccelerationMagMean
-	FrequencyBodyAccelerationMagStd
-	FrequencyBodyAccelerationMagMeanFreq
-	FrequencyBodyBodyAccelerationJerkMagMean
-	FrequencyBodyBodyAccelerationJerkMagStd
-	FrequencyBodyBodyAccelerationJerkMagMeanFreq
-	FrequencyBodyBodyGyroMagMean
-	FrequencyBodyBodyGyroMagStd
-	FrequencyBodyBodyGyroMagMeanFreq
-	FrequencyBodyBodyGyroJerkMagMean
-	FrequencyBodyBodyGyroJerkMagStd
-	FrequencyBodyBodyGyroJerkMagMeanFreq

Measurement for the derived features:
=========================================
A variable that was estimated from the mean and standard deviation of the original signals is: 

- avg(): average value


The complete list of avg() variable for each feature vector is available in 'myfeatures.txt'
