---
title: "ReadMe"
author: "Ben"
date: "Wednesday, October 22, 2014"
output: html_document
---
Information on our run_analysis.R:
======================================

run_analysis.R used datasets from www.smartlab.ws to create a tidy dataset. The run_analysis.R first loads test and training datasets from SmartLabs, and then those datasets are merged into a single dataset. Measurements that are mean and standard deviation of the original signal from the merged dataset is extracted to form a subset of dataset with 10299 observations and 81 variables (79 feature variables + subject + activity). A tidy dataset is obtained by taking an average of the aforementioned extracted data based on different combination of subject and activity. The tidy dataset is saved into a variable "Xy_by_group".

- subject: contain label values for the group of 30 volunteers.
- activity: contatin labels for the six actions;1) WALKING, 2) WALKING_UPSTAIRS, 3) WALKING_DOWNSTAIRS, 4) SITTING, 5) STANDING, 6) LAYING

Detail on SmartLabs' experiment:
======================================
SmartLabs' experiments have been carried out with a group of 30 volunteers within an age bracket of 19-48 years. Each person performed six activities (WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING) wearing a smartphone (Samsung Galaxy S II) on the waist. Using its embedded accelerometer and gyroscope, we captured 3-axial linear acceleration and 3-axial angular velocity at a constant rate of 50Hz. The experiments have been video-recorded to label the data manually. The obtained dataset has been randomly partitioned into two sets, where 70% of the volunteers was selected for generating the training data and 30% the test data. 

The sensor signals (accelerometer and gyroscope) were pre-processed by applying noise filters and then sampled in fixed-width sliding windows of 2.56 sec and 50% overlap (128 readings/window). The sensor acceleration signal, which has gravitational and body motion components, was separated using a Butterworth low-pass filter into body acceleration and gravity. The gravitational force is assumed to have only low frequency components, therefore a filter with 0.3 Hz cutoff frequency was used. From each window, a vector of features was obtained by calculating variables from the time and frequency domain. See 'features_info.txt' for more details. 

For each record it is provided:

- Triaxial acceleration from the accelerometer (total acceleration) and the estimated body acceleration.
- Triaxial Angular velocity from the gyroscope. 
- A 561-feature vector with time and frequency domain variables. 
- Its activity label. 
- An identifier of the subject who carried out the experiment.

My GitHub includes the following files:
=========================================

- 'README.rmd'
- 'CookBook.rmd': Explanation on the variables.
- 'myfeatures.txt': List of all features.

- 'run_analysis.R': a R file that loads and merges test and training dataset from Smartlab. The data is then processed to create a tidy data set.

- 'TidyData.txt': Table of clean data generated by run_analysis.R.

Notes: 
======
- Features are normalized and bounded within [-1,1].
- Each feature vector is a row on the text file.

For more information about the source dataset contact: activityrecognition@smartlab.ws